### ISSUE TITLE
[BUG] Unable to build rds_data

### ISSUE THREAD

**Issue by NyanKiyoshi** [vemel/mypy_boto3_builder#23]
**Describe the bug**
Docs of [mypy-boto3-rds_data](https://pypi.org/project/mypy-boto3-rds-data/#description) says to run `mypy_boto3` but outputs the following exception:
```
Traceback (most recent call last):
  File "/Venvs/Cloud/bin/mypy_boto3", line 11, in <module>
    load_entry_point('mypy-boto3==1.13.6.0', 'console_scripts', 'mypy_boto3')()
  File "/Venvs/Cloud/lib/python3.8/site-packages/mypy_boto3/main.py", line 131, in main
    build_package_stubs(submodule, logger)
  File "/Venvs/Cloud/lib/python3.8/site-packages/mypy_boto3/main.py", line 311, in build_package_stubs
    submodule_path / "__init__.py", _get_proxy_contents(submodule.module_name), logger,
  File "/Venvs/Cloud/lib/python3.8/site-packages/mypy_boto3/main.py", line 170, in _get_proxy_contents
    service_module = importlib.import_module(module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Venvs/Cloud/lib/python3.8/site-packages/mypy_boto3_rds_data/__init__.py", line 17, in <module>
    from mypy_boto3_rds_data.client import RDSDataServiceClient, RDSDataServiceClient as Client
  File "/Venvs/Cloud/lib/python3.8/site-packages/mypy_boto3_rds_data/client.py", line 17, in <module>
    from mypy_boto3_rds_data.type_defs import (
  File "/Venvs/Cloud/lib/python3.8/site-packages/mypy_boto3_rds_data/type_defs.py", line 89, in <module>
    "StructValueTypeDef", {"attributes": List[ValueTypeDef]}, total=False
NameError: name 'ValueTypeDef' is not defined
```

Lines 88-90 should be transformed to a lazy typing:
```patch
StructValueTypeDef = TypedDict(
-    "StructValueTypeDef", {"attributes": List[ValueTypeDef]}, total=False
+    "StructValueTypeDef", {"attributes": List["ValueTypeDef"]}, total=False
)
```

**To Reproduce**
1. Install 'boto3-stubs[rds-data]'
2. Run `mypy_boto3`

**Additional context**
```shell
> uname -rs
Darwin 19.4.0

> pip freeze | grep mypy
mypy-boto3==1.13.6.0
mypy-boto3-builder==1.0.9
mypy-boto3-cloudformation==1.13.6.0
mypy-boto3-dynamodb==1.13.6.0
mypy-boto3-ec2==1.13.6.0
mypy-boto3-lambda==1.13.6.0
mypy-boto3-rds==1.13.6.0
mypy-boto3-rds-data==1.13.6.0
mypy-boto3-s3==1.13.6.0
mypy-boto3-sqs==1.13.6.0
```

**Comment by vemel** [comment]
I have never used this service. I am going to fix this issue and add a small integration test. Thank you for report.

**Comment by vemel** [comment]
Fixed in master, going to release

**Comment by vemel** [comment]
Fixed in the latest version. I did not add an integration test, but tested manually. TypedDicts in `type_defs.py` are now sorted alphabetically for easier lookup.

Let me know if it works for you and sorry it took so long.

**Comment by NyanKiyoshi** [comment]
Thanks! It works now.
