### ISSUE TITLE
[BUG] sys not defined in type_defs.py

### ISSUE THREAD

**Issue by ryanhiebert** [vemel/mypy_boto3_builder#51]
**To Reproduce**
1. Install 'boto3-stubs[essential,sts]'
2.  Run the following code

```pycon
>>> import mypy_boto3_sts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ryan/.local/share/virtualenvs/aspiredu-sa7rbeeh/lib/python3.8/site-packages/mypy_boto3_sts/__init__.py", line 19, in <module>
    from mypy_boto3_sts.client import STSClient
  File "/home/ryan/.local/share/virtualenvs/aspiredu-sa7rbeeh/lib/python3.8/site-packages/mypy_boto3_sts/client.py", line 18, in <module>
    from mypy_boto3_sts.type_defs import (
  File "/home/ryan/.local/share/virtualenvs/aspiredu-sa7rbeeh/lib/python3.8/site-packages/mypy_boto3_sts/type_defs.py", line 14, in <module>
    if sys.version_info >= (3, 8):
NameError: name 'sys' is not defined
```

Version info:

```
        "mypy-boto3-sts": {
            "hashes": [
                "sha256:7e83ba0699346ca92f54cdb4084d33ee100bb8248d109f919615aa153589dbb9",
                "sha256:97fa61a2c8d1d1526722c8b8f3bb208172c6fa062dc314d16bd7df31a4e2fce5"
            ],
            "version": "==1.15.12.1"
        },
```

**Comment by vemel** [comment]
Thanks for the report, I will take a look.

**Comment by vemel** [comment]
Fixed in the latest release. Please let me know if it works for you.

**Comment by ryanhiebert** [comment]
Works for me, thank you!
